baseURL = "https://blog.binaergewitter.de/"
relativeURLs = false
canonifyURLs = false
uglyURLs = false
disablePathToLower = true
languageCode = "de"
title = "Binärgewitter"

[outputs]
  home = ["HTML", "RSS", "JSON", "LatestShow"]

[author]
  name = "Binärgewitter Team"

[params]
  author = "Binärgewitter Team"
  description = "Ein Podcast, der sich mit dem Web, Technologie und Open Source Software auseinander setzt."
  isso = true
  items_on_index = 3
  archived_on_index = 10
  date_format = "02.01.2006"

  [params.contributors]
    ingo = { name = "Ingo Ebel" }
    pfleidi = { name = "Sven Pfleiderer" }
    makefu = { name = "Felix Richter" }
    madmas = { name = "Markus Schlichting" }
    rb2k = { name = "Marc Seeger" }
    ranterle = { name = "Matthias Wenz" }
    l33tname = { name = "Felix" }
    hadez = { name = "hadez" }
    jancborchardt = { name = "Jan-Christoph Borchardt" }
    schmittlauch = { name = "Trolli Schmittlauch" }
    kreativmonkey = { name = "Sebastian Preisner" }
    ngc_ollie = { name = "Carsten alias NGC-Ollie" }

[permalinks]
  post = "/:year/:month/:day/:slug"
  pages = "/pages/:slug"
  category = "/podcast_feed/:slug"

  [outputFormats.RSS]
    baseName = "rss"
    mediaType = "application/rss+xml"
  [outputFormats.LatestShow]
    baseName = "latest-show"
    mediaType = "text/plain-nosuffix"
    isPlainText = true
    notAlternative = true

[mediaTypes]
  [mediaTypes."application/rss+xml"]
    suffixes = ["xml"]
  [mediaTypes."text/plain-nosuffix"]
    suffixes = [""]
    delimiter = ""

[taxonomies]
  category = "categories"

[module]
  [[module.mounts]]
    source = "articles"
    target = "content/post"
  [[module.mounts]]
    source = "pages"
    target = "content/pages"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "static/img"
    target = "static/images"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "content"
    target = "content"

[security]
  [security.http]
    methods = ["GET"]
    allowedHosts = ["download.binaergewitter.de"]

[frontmatter]
  date = [":filename"]
  publishDate = [":filename"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
